# Generated by Django 5.2.7 on 2025-11-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pending_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='temp_reminder_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
