# Generated by Django 5.2.7 on 2025-10-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_userprofile_role_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('caregiver', 'Caregiver'), ('donor', 'Donor')], max_length=20, null=True),
        ),
    ]
