# Generated by Django 5.2.7 on 2025-11-10 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_userprofile_pending_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='location',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name',
        ),
        migrations.AddField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(default='Untitled Resource', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contacts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('education', 'Sickle Cell Education'), ('emergency', 'Emergency Guide'), ('nutrition', 'Nutrition & Hydration'), ('pain', 'Pain Management'), ('mental', 'Mental Health'), ('caregiver', 'Caregiver Guide')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
