# Generated by Django 5.2.7 on 2025-11-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contacts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
